### ISSUE TITLE
CONTRIBUTING.md import rules conflict

### ISSUE THREAD

**Issue by ajite** [OCA/maintainer-tools#119]
There is a conflict between these two rules:

**Rule 1:**
> The imports are ordered as

> 1. Externals libs (One per line sorted and splitted in python stdlib)
> 2. Imports of `openerp`
> 3. Imports from Odoo modules (rarely, and only if necessary)
> 4. Local imports in the relative form

> Inside these 4 groups, the imported lines are alphabetically sorted.

**Rule 2:** 

> In python files where you use a `import external_dependency_python_N` you will need to add a `try-except` with a debug log.

> ```python
 try:
  import external_dependency_python_N
except ImportError:
  _logger.debug('Can not `import external_dependency_python_N`.')
```

You should import the logger before other libraries. Otherwise you will not be able to do the `logger.debug` in the `try-except`.
My idea would be to modify the CONTRIBUTING.MD to include that the `logging` library needs to be the first library to be imported. What do you think?

**Comment by pedrobaeza** [comment]
Perfect. Better explicit than implicit

**Comment by guewen** [comment]
Here's what pep8 says:

>  Imports should be grouped in the following order:
* standard library imports
* related third party imports
* local application/library specific imports

> You should put a blank line between each group of imports. 

So it should not be a problem, logging will always be before third party dependencies. Rather than a rule specifically for `logging`, we should say:

1. standard library imports
1. related third party imports
1. Odoo imports
1. Imports from Odoo modules (rarely, and only if necessary)
1. Local imports in the relative form

**Comment by ajite** [comment]
@guewen That is indeed a better solution :)! :+1:

**Comment by ajite** [comment]
I made a pull request for that #121 . Let's continue the discussion in it.
