### ISSUE TITLE
Proposal: Improve Contributing Guidelines and OCA website

### ISSUE THREAD

**Issue by rafaelbn** [OCA/maintainer-tools#159]
Hello:

First of all thanks to all OCA by this hardwork.

I would like to propose a change in:

- https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md
- https://odoo-community.org/page/bugs
- https://odoo-community.org/page/code

I think every contributor must read the CONTRIBUTING.md and defining the same structure in the tiitle of issues and PRs will help us a lot when: (1) someone searching for a issue that already exists (2) reviewing issues or PRs. It will make our life better.

1. Version: it's writed, all issues and PRs tittles must begin with versión like [8.0][9.0]
2. Why?:
   - [ADD]: add new module to the project
   - [FIX]: fix a module in the project
   - [IMP]: improve the functionality of the module
3. Which? Shows the name of the module [name_of_the_module]
4. What? Description of the module.

### In website /bugs:

> 3) Describe your bug
> 
> Before creating a new issue in the Github repository, make sure it is not already reported by browsing the list.
You can seach by module's name in the tittle
> 
> Then, create a new issue, with the following information:

Then, create a new issue, you have two ways:

* Every module has in the README a Bugtracker which will open you a issue in Github ready to describe

![captura](https://cloud.githubusercontent.com/assets/8736623/11259317/f3eaff1e-8e60-11e5-8e72-778673dc22bc.PNG)

![captura1](https://cloud.githubusercontent.com/assets/8736623/11259319/fb8ea5e0-8e60-11e5-8c72-9ce64d1fe850.PNG)

* Create a new issue manually wit the following information:

> 
>     a title: enter the Odoo version between bracket and the last line of the error message 

a tittle: enter the Odoo version, why and module's name, each one between braket and the las line of the error message as i the example:
-Version: [8.0]
-Why: [BUG]
-Module's name: [website_signup_legal_page_required]
-Description: Internal Server Error when signing up

>     a description : describe the bug
>     the steps to reproduce
>     the result you experienced with the complete error message
>     the result you expected

```
module: website_signup_legal_page_required
version: 8.0
**Steps to reproduce**
- ...
**Current behavior**
**Expected behavior**
```

> Other contributors may ask you for further information to qualify your bug before working on a fix. > Make sure to answer them. If you have the skills, please code the fix and share it.

### In website /code:

> 4) Push your code and create a pull request

Please set tittle of PR like:

1. Version: it's writed, all issues and PRs tittles must begin with versión like [8.0][9.0]
2. Why?:
   - [ADD]: add new module to the project
   - [FIX]: fix a module in the project
   - [IMP]: improve the functionality of the module
3. Which? Shows the name of the module [name_of_the_module]
4. What? Description of the module.

> Once you committed your changes in your local branch, you can publish it by pushing it to your Github repository.
>Read our FAQ to determine the best open source license for your module.
> Once your branch is on Github, you can create a pull request against the OCA branch

Let me know

Thanks

**Comment by max3903** [comment]
Hello Rafael, 

To improve CONTRIBUTING.md , you need to make a pull request. 

For the website, I will take care of it. 

Thanks! 
-- 
Maxime Chambreuil 
+1 (514) 276-5468 #126 

----- Le 18 Nov 15, à 20:19, Rafael Blasco <notifications@github.com> a écrit : 



Hello: 

First of all thanks to all OCA by this hardwork. 

I would like to propose a change in: 

    * https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md 
    * https://odoo-community.org/page/bugs 
    * https://odoo-community.org/page/code 


I think every contributor must read the CONTRIBUTING.md and defining the same structure in the tiitle of issues and PRs will help us a lot when: (1) someone searching for a issue that already exists (2) reviewing issues or PRs. It will make our life better. 

    1. Version: it's writed, all issues and PRs tittles must begin with versión like [8.0][9.0] 
    2. Why?: 
        * [ADD]: add new module to the project 
        * [FIX]: fix a module in the project 
        * [IMP]: improve the functionality of the module 
    3. Which? Shows the name of the module [name_of_the_module] 
    4. What? Description of the module. 
In website /bugs: 




3) Describe your bug 

Before creating a new issue in the Github repository, make sure it is not already reported by browsing the list. 
You can seach by module's name in the tittle 

Then, create a new issue, with the following information: 



Then, create a new issue, you have two ways: 

    * Every module has in the README a Bugtracker which will open you a issue in Github ready to describe 








    * Create a new issue manually wit the following information: 

BQ_BEGIN

a title: enter the Odoo version between bracket and the last line of the error message 

BQ_END


a tittle: enter the Odoo version, why and module's name, each one between braket and the las line of the error message as i the example: 
-Version: [8.0] 
-Why: [BUG] 
-Module's name: [website_signup_legal_page_required] 
-Description: Internal Server Error when signing up 
BQ_BEGIN

a description : describe the bug
the steps to reproduce
the result you experienced with the complete error message
the result you expected 

BQ_END

module: website_signup_legal_page_required
version: 8.0
**Steps to reproduce**
- ...
**Current behavior**
**Expected behavior** 

BQ_BEGIN


Other contributors may ask you for further information to qualify your bug before working on a fix. > Make sure to answer them. If you have the skills, please code the fix and share it. 
BQ_END
In website /code: 

BQ_BEGIN


4) Push your code and create a pull request 
BQ_END


Please set tittle of PR like: 

    1. Version: it's writed, all issues and PRs tittles must begin with versión like [8.0][9.0] 
    2. Why?: 
        * [ADD]: add new module to the project 
        * [FIX]: fix a module in the project 
        * [IMP]: improve the functionality of the module 
    3. Which? Shows the name of the module [name_of_the_module] 
    4. What? Description of the module. 

BQ_BEGIN


Once you committed your changes in your local branch, you can publish it by pushing it to your Github repository. 
Read our FAQ to determine the best open source license for your module. 
Once your branch is on Github, you can create a pull request against the OCA branch 
BQ_END


Let me know 

Thanks

**Comment by max3903** [comment]
Hello Rafael, 

I have updated the screenshots and text on the bugs page, but the rest of the modifications should go into the CONTRIBUTING.md. 

Please do not forget that those pages are for newcomers. If you expect them to read the CONTRIBUTING.md before contributing, we won't get many contributions. They will make mistakes anyway and that is fine, we all did and still do sometimes. It leaves rooms for teaching/coaching/mentoring between new and existing contributors. This way, newcomers will discover the conventions one step at a time and won't feel discouraged. It also helps to grow the belonging feeling among contributors. 

Cheers, 
-- 
Maxime Chambreuil 
+1 (514) 276-5468 #126 

----- Le 19 Nov 15, à 11:33, Maxime Chambreuil <maxime.chambreuil@savoirfairelinux.com> a écrit : 

Hello Rafael, 

To improve CONTRIBUTING.md , you need to make a pull request. 

For the website, I will take care of it. 

Thanks! 
-- 
Maxime Chambreuil 
+1 (514) 276-5468 #126 

----- Le 18 Nov 15, à 20:19, Rafael Blasco <notifications@github.com> a écrit : 



Hello: 

First of all thanks to all OCA by this hardwork. 

I would like to propose a change in: 

    * https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md 
    * https://odoo-community.org/page/bugs 
    * https://odoo-community.org/page/code 


I think every contributor must read the CONTRIBUTING.md and defining the same structure in the tiitle of issues and PRs will help us a lot when: (1) someone searching for a issue that already exists (2) reviewing issues or PRs. It will make our life better. 

    1. Version: it's writed, all issues and PRs tittles must begin with versión like [8.0][9.0] 
    2. Why?: 
        * [ADD]: add new module to the project 
        * [FIX]: fix a module in the project 
        * [IMP]: improve the functionality of the module 
    3. Which? Shows the name of the module [name_of_the_module] 
    4. What? Description of the module. 
In website /bugs: 




3) Describe your bug 

Before creating a new issue in the Github repository, make sure it is not already reported by browsing the list. 
You can seach by module's name in the tittle 

Then, create a new issue, with the following information: 



Then, create a new issue, you have two ways: 

    * Every module has in the README a Bugtracker which will open you a issue in Github ready to describe 








    * Create a new issue manually wit the following information: 

BQ_BEGIN

a title: enter the Odoo version between bracket and the last line of the error message 

BQ_END


a tittle: enter the Odoo version, why and module's name, each one between braket and the las line of the error message as i the example: 
-Version: [8.0] 
-Why: [BUG] 
-Module's name: [website_signup_legal_page_required] 
-Description: Internal Server Error when signing up 
BQ_BEGIN

a description : describe the bug
the steps to reproduce
the result you experienced with the complete error message
the result you expected 

BQ_END

module: website_signup_legal_page_required
version: 8.0
**Steps to reproduce**
- ...
**Current behavior**
**Expected behavior** 

BQ_BEGIN


Other contributors may ask you for further information to qualify your bug before working on a fix. > Make sure to answer them. If you have the skills, please code the fix and share it. 
BQ_END
In website /code: 

BQ_BEGIN


4) Push your code and create a pull request 
BQ_END


Please set tittle of PR like: 

    1. Version: it's writed, all issues and PRs tittles must begin with versión like [8.0][9.0] 
    2. Why?: 
        * [ADD]: add new module to the project 
        * [FIX]: fix a module in the project 
        * [IMP]: improve the functionality of the module 
    3. Which? Shows the name of the module [name_of_the_module] 
    4. What? Description of the module. 

BQ_BEGIN


Once you committed your changes in your local branch, you can publish it by pushing it to your Github repository. 
Read our FAQ to determine the best open source license for your module. 
Once your branch is on Github, you can create a pull request against the OCA branch 
BQ_END


Let me know 

Thanks

**Comment by rafaelbn** [comment]
Hello Max,

You are right. Then It would be better to let contribute and after that take the one who is more active and teach her/him to do it better.

Thanks a lot for you changes.

Regards
