### ISSUE TITLE
[RFC] Contribution: Merger Commit Squashing

### ISSUE THREAD

**Issue by lasley** [OCA/maintainer-tools#248]
We have all likely noticed these awesome new Github `Squash and merge` & `Rebase and merge` options, and I think we all agree they are freaking awesome.

I have recently run into some instances of these features being used in ways that are detrimental, and feel that we need to start defining some rules on how we use these. Please see the following for an example of why I am bringing this up:
* https://github.com/OCA/server-tools/issues/619
* https://github.com/OCA/server-tools/issues/636

Another thing with squash & merge is that it destroys any cryptographic signatures that may have been purposefully applied by the committer. Due to this, I prefer to squash my own commits in order to maintain integrity of my commit.

That said, I'm sure this isn't the case with everybody. I'm insanely OCD when it comes to this sort of this, mainly because I've been put in the position many times where someone has made a mistake on a squash/rebase, but it's linked to me because of the wizardry that is timeline editing.

I'm not sure how to solve this problem of preference vs necessity though. The squash and merge is so incredibly helpful when dealing with newer contributors, because the whole squashing thing is a definite detractor in terms of contribution. But how do we apply this in some sort of manor that still allows the people that do want to squash to do so?

**Comment by rafaelbn** [comment]
Usually we must ask contributors to squash their selves

**Comment by lmignon** [comment]
I'm personally against the squash of commits of others and have a lot of times expressed my opinion on this topics when reviewers asked me to do this during module migrations. IMO we must keep the commit history when merging prs AND when we migrate modules

**Comment by pedrobaeza** [comment]
That's a nonsense to keep a lot of "PEP8 fix", "Fix onchange" and so on commits. They are useless and make the size of the repository unmanageable when we reach 5 or 6 version branches (it's already passing in l10n-spain, that has branches from 4.2 - the size has gone to 150 MB for that repository). We don't have to blindly squash, but also we don't have to keep all the history as the development/review has come to the module.

**Comment by JonathanNEMRY** [comment]
@pedrobaeza I fully agree with the fact that "pep8 fix" is not clean into a commit history.

But I'am not in favor by forcing users to squash existing commits into migration or existing source history.
Also I suggest to do it when you are into a review and with the implied commits of the PR only: "pep8 fix" should't be committed at all by the developer that is applying the changes for its review into the linked pull request. (as @lasley said, there are many tools into Git to avoid committing that kind of stuff) So IMO that's exactly the place where we have to change/allow to ask something more.

But we have to be careful with existing commits that appears as beeing "not-clean" (implying some size addition too...) because of a "pep8 fix" label as they possibly contain more than a simple "pep8 fix" and then it became sensitive to ask some change about these commits (added time and authors issue)

**Comment by pedrobaeza** [comment]
The problem is that in the past we haven't applied that rule in the past, and now we are transferring the dirty commit history across branches. Take into account that this doubles the size of the repository, as the commits are not cherry-pick, but extracted by folder, so although the diff can be identical, the commit has another hash and counts as another one.

We have also the "OCA Transbot translations" commits, that can accumulate a lot of commits during the lifecycle of the version.

Those 2 are the reasons for me to ask a squash of the commits when migrating a module. You can agree with me about the second one, isn't it? And about the first, if we do it in this way and properly treat the v9 commit history, for v10 we won't have this problem again (except for the point 1, that will always happen).

**Comment by moylop260** [comment]
I like to merge&squash from github.

I don't like squash commits before merge:
 - If I'm have a active revision I like to see the new commits to know what exactly changed. (Avoid review all changes again)
 - If other reviewer is agree with a old version we can use the first commit instead of request revert it
   - Example: https://github.com/odoo/odoo/pull/12769

However, I understand the good point of @lasley 

Then we should have a open door for this cases.
What about the following rules table?

| Commits | PR comment "please, don't squash" | How to merge                     |
|---------|-----------------------------------|----------------------------------|
| >1       | Yes                               | Developer squash after approvals |
| >1     | No                                | Merger Squash&merge              |
| 1       | Yes                               | Merger Merge original commit     |
| 1       | No                                | Merger Squash&merge              |

**Comment by lmignon** [comment]
@moylop260 You must also consider when the PR has more than 1 author. In this case you must preserve the credit of all the authors.

**Comment by moylop260** [comment]
@lmignon You are right!
Thank you

Point 1 changed
```patch
- Developer squash after approvals
+ Developer squash after approvals --by author-- 
```

**Comment by lasley** [comment]
Given @lmignon's point, we also cannot use the Github Squash options. This was the cause of https://github.com/OCA/server-tools/issues/619

**Comment by pedrobaeza** [comment]
We can only use it when there's only one contributor in the PR, which happens a lot with new modules or patches that are done in several steps, so the button worths the while.

**Comment by lmignon** [comment]
@pedrobaeza I've a little bit analyzed the l10n-spain repository. IMO It appears that the problem of size that you encounter with this repository is not related to the number of commits. The problem is that you've stored in your repository a lot of large files.... (jar, csv, )
Takes a look at  http://naleid.com/blog/2012/01/17/finding-and-purging-big-files-from-git-history to analyze your repository first...

**Comment by pedrobaeza** [comment]
I know that big files, but we could save a lot because of some diff files on these large files that could be squashed across versions, so another more reason for doing it.

**Comment by lmignon** [comment]
So the rule is not global and this problem must be addressed on a per repo/pr basis.

**Comment by pedrobaeza** [comment]
No, the rule can be global: squash what you can, and you'll save some bytes to be transferred, some trees to be cut, and why not, some kitties :stuck_out_tongue_closed_eyes:

**Comment by yvaucher** [comment]
+1 @lmignon 

To come back on this I think it should be up to the commiter to decide. There are some case where a commit squashing makes sense. Mostly when the PR is kind of messy and we want to merge it. Asking to a new developer to solve it leads to a dead-end as there could be a gab in knownledge from creating a commit and mastering amending and rebase tools.
I agree it's better to teach to fish instead of giving the fishes but for important fixes and for most wanted features the commiter can (is not forced to) ease a part of the job.

**Comment by dreispt** [comment]
I also agree that it really depend and must decided per PR.
Having said that, blindly squashing commits should _not_ be recommended.

**Comment by pedrobaeza** [comment]
GitHub offers now the possibility to the repo writers of modifying PR branch, so we can do the work instead the newbies. A clean commit history is very important in my opinion for avoiding unmanageable repos in a couple of versions more.

**Comment by lasley** [comment]
I feel like when someone squashes my commits, the message is significantly less meaningful than if I would have squashed it myself though. The same `Fix my dumbness` comments still make their way into the history, just as one comment instead of multiple.

**Comment by lasley** [comment]
I'm going to go ahead and close this - I feel that the [new Wiki entry](https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests) is a great start & any additional changes should be made direct there. Thanks everyone!
