### ISSUE TITLE
installing a module from github using pip installs all modules in the repo

### ISSUE THREAD

**Issue by jbeficent** [OCA/maintainer-tools#329]
### Milestone (Odoo version)
- 10.0

if you do:
pip install -r requirements.txt
using requirements.txt with the following content:
git+https://github.com/OCA/web.git@10.0#egg=odoo10_addon_web_tree_many2one_clickable&subdirectory=setup/web_tree_many2one_clickable

Will install in the python environment the following folder:
python_environment/src/odoo10-addon-web-tee-many2one-clickable
But inside that folder, it will contain code for all the modules of https://github.com/OCA/web.git@10.0

Is this the normal behaviour? One would expect that only the one module listed in subdirectory=setup/web_tree_many2one_clickable would appear.

cc @lmignon @sbidoul perhaps you know

**Comment by sbidoul** [comment]
This is how pip subdirectory option works indeed.

Since you are installing a module from the main 10.0 branch, it's best to install it from pypi: `pip install odoo10-addon-web_tree_many2one_clickable`.

Editable installs from git is best reserved for unreleased branches.

During developpement you can install from your local directory with `pip install -e mylocalcopyofweb/setup/web_tree_many2one_clickable`.
