### ISSUE TITLE
Please also build and upload source tarball to pypi (not only wheels)

### ISSUE THREAD

**Issue by rhertzog** [OCA/maintainer-tools#331]
As discussed with @sbidoul in https://github.com/acsone/setuptools-odoo/issues/24#issuecomment-372775038 it would be interesting to modify your automation to also build and upload release tarballs of the OCA modules, and not only the wheels.

The reason I ask this is that (proper) Debian packaging relies on having release tarballs with a setup.py that works outside of any git repository.

**Comment by sbidoul** [comment]
Tasks
- [ ] add metapackage generation setuptools-odoo-makedefaults https://github.com/acsone/setuptools-odoo/issues/25
- [ ] deprecate https://wheelhouse.odoo-community.org/oca/ in favor of https://wheelhouse.odoo-community.org/oca-simple
- [x] simple script `build-to-simple` to build sdist + wheel to a simple index (cfr @sbidoul)
- [ ] rework and rename [bdist_all_wheels](https://github.com/OCA/maintainer-tools/blob/78605b82d19e7f9c181d1c4c06b69f8135d4914d/tools/bdist_all_wheels.py)
  - [ ] delegate meta package creationg to setuptools-odoo-makedefaults
  - [ ] detect file removals in `setup/**` and push them to git
  - [ ] use `build-to-simple` to build to /oca-simple instead of /oca
  - [ ] build sdist in addition to wheels

**Comment by rhertzog** [comment]
On Mon, 23 Apr 2018, Stéphane Bidoul (ACSONE) wrote:
> I'm not pushing that to pypi yet because I'd like to give them some incubation time. Do you need them on pypi to test deb packaging (https://wheelhouse.odoo-community.org/oca-simple/ behaves as a pypi simple index)?

No, I don't need them on pypi. I can track updates from almost any URL
where I have a listing of available tarballs.

Cheers,
-- 
Raphaël Hertzog ◈ Debian Developer

Support Debian LTS: https://www.freexian.com/services/debian-lts.html
Learn to master Debian: https://debian-handbook.info/get/

**Comment by pedrobaeza** [comment]
@sbidoul is this completed?

**Comment by sbidoul** [comment]
yes, closing.
