### ISSUE TITLE
What's the convention on email template records? Should they be non-updatable or not?

### ISSUE THREAD

**Issue by ivantodorovich** [OCA/maintainer-tools#375]
I can't find a convention on this topic.

I've seen most modules include email template records using the `noupdate=1` flag, but I'm not sure if it's the best approach. It makes them impossible to update via updates, and may lead to unfixable bugs or improvements in the templates itself (via regular updates, at least).

I think a good alternative to this is to not use the `noupdate=1` flag. This, of course, makes it hard for the user to edit the template. But he can manually set the `noupdate` flag by editing the `ir.model.data` record in his own instance. It's trickier, no doubt about it, but let's the user decide. Maybe there could be a module to make it easier, showing warnings when editing updatable `mail.templates` and providing an easy way to make them non-updatable.

What's your opinion on this?

**Comment by hbrunn** [comment]
I think `noupdate="1"` is what we should do, and for cases where things really would break without, you can provide a pre migration script that resets the `noupdate` flag.

Your proposal would really need some support module, because most users editing mail templates probably won't have permissions to edit `ir.model.data`.

**Comment by pedrobaeza** [comment]
I agree with @hbrunn

**Comment by ivantodorovich** [comment]
Yeah, you're right. Without a support module it wouldn't be practical at all.
Thanks!
