### ISSUE TITLE
[WiKi][FIX] Use temporary reference(s) to another pull request(s) - link structure

### ISSUE THREAD

**Issue by mymage** [OCA/maintainer-tools#552]
On the referenced page there is template of the link to use:
`odoo-addon-<module_name_with_dashes> @ git+https://github.com/OCA/<repository>/refs/pull/<PR_number>/head#subdirectory=setup/<module_name>`
For newbie like me I suggest to change it to:
`odoo-addon-<module_name_with_dashes> @ git+https://github.com/OCA/<repository>`**.git@**`refs/pull/<PR_number>/head#subdirectory=setup/<module_name`**_with_dashes**`>`

@pedrobaeza 

Thanks

**Comment by pedrobaeza** [comment]
Hi, @mymage. If I look at the setup folder of any repository, I see the folder with underscores, not dashes:

https://github.com/OCA/l10n-spain/tree/15.0/setup

So I think it's correct right now.

**Comment by mymage** [comment]
Hola @pedrobaeza I apologize, you are right for module name, I copied/wrote it wrong.

But on PR https://github.com/OCA/management-system/pull/498 still open I used the format
`odoo-addon-<module_name`**_with_underscore**`> @ git+https://github.com/OCA/<repository>`**.git@**`refs/pull/<PR_number>/head#subdirectory=setup/<module_name`**_with_underscore**`>` and it works.
I don't know if the initial `odoo-addon-*` part depends on the repo.

The `<repository>/refs` part on the wiki I think it is wrong at least for the **/** that has to be  **@**, the **.git** is only to evidence the difference beween the "name" of the repository and the "object" (for us newbie).

Thanks

**Comment by chienandalu** [comment]
Having similar issues with another PR (https://github.com/OCA/survey/pull/66/commits/986a1f646159d0a9cd02129ae95a00b0c4b843d9), another point to take into account is how the repository modules are packed. In my case, had to to prefix my requirement with `odoo13-addon-` (maybe @sbidoul can enlighten us on why this difference between repositories, that I guess it has to do with this https://github.com/acsone/setuptools-odoo#versioning although I don't fully understand it :sweat_smile: )

**Comment by sbidoul** [comment]
Hi @chienandalu. For Odoo < 15, PyPI package names are constructed as `odoo{series}-addon-addon_name`. For Odoo >= 15, it is `odoo-addon-addon_name`.

The reason we could do this change, is that the pip dependency resolver is now smart enough to pick-up the correct addon version based on the installed Odoo version, so we can now have the same package name across version, which is simpler and avoid to create a whole new set of PyPI project for each new Odoo version.

@mymage 
- Underscores vs dashes in package names don't matter for python packaging, but in the subdirectory part, it is important to use underscores, since it is the directory name, so it's better to user underscores in addon names.
- The `.git` suffix in the repository URL should not matter for GitHub.

**Comment by chienandalu** [comment]
Thanks for the heads up @sbidoul ! All clear now :+1:

**Comment by pedrobaeza** [comment]
Updated according this: https://github.com/OCA/maintainer-tools/wiki/Use-temporary-reference(s)-to-another-pull-request(s)
